# Generated by Django 5.0.1 on 2024-02-07 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trans_parse_process', '0002_shortclip_slug_video_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcript',
            name='structured_transcript',
        ),
        migrations.RemoveField(
            model_name='video',
            name='processed',
        ),
    ]
