# Generated by Django 5.0.1 on 2024-02-08 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans_parse_process', '0004_alter_shortclip_video_chunk_delete_transcript'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(unique=True, upload_to='videos/'),
        ),
    ]
