# Generated by Django 5.0.1 on 2024-02-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans_parse_process', '0006_alter_video_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(default='default_image.png', upload_to='thumbnails'),
        ),
    ]
