# Generated by Django 5.0.1 on 2024-02-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans_parse_process', '0009_alter_shortclip_clip_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='topic',
            field=models.CharField(default='General', max_length=255),
        ),
    ]
