# Generated by Django 5.0.1 on 2024-02-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans_parse_process', '0010_video_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='topic',
            field=models.CharField(choices=[('science', 'Science'), ('technology', 'Technology'), ('education', 'Education'), ('health', 'Health'), ('entertainment', 'Entertainment'), ('other', 'Other')], default='other', max_length=255),
        ),
    ]
